#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/logs/weixinpay/app/*.log
  fields:
    log_topic: weixinpay_log
    document_type: weixinpay
#  scan_frequency: 60s
#  backoff: 10s
#================================ General ====================================== 
#  queue:
#    mem:
#      events: 10240
#      flush.min_events: 12288
#      fulsh.timeout: 60s


#================================ Outputs =====================================
#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000
#xpack.monitoring:
#  enabled: true
#  elasticsearch:
#    hosts: ["http://172.16.10.40:9200", "http://172.16.10.43:9200" ,"http://172.16.10.223:9200"]