#=========================== Filebeat prospectors =============================

filebeat.inputs:
- type: log
  paths:
    - /ubox/logs/coupon/app/exception.log
  fields:
    log_topic: coupon_log
    document_type: coupon
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /ubox/logs/coupon/app/framework.log
  fields:
    log_topic: coupon_log
    document_type: coupon
    
- type: log
  paths:
    - /ubox/logs/crm-java/app/framework.log
  fields:
    log_topic: crm_java_log
    document_type: crm_java
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  
  
- type: log
  paths:
    - /ubox/logs/cardpay/app/framework.log
    - /ubox/logs/cardpay/app/exception.log
  fields:
    log_topic: cardpay_log
    document_type: cardpay
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
#================================ Outputs =====================================
#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000