#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/logs/ybk_inter_backend/app/ybk_inter_work.log
  fields:
    log_topic: ybk_inter_log
    document_type: ybk_inter
  ignore_older: 24h

- type: log
  paths:
    - /ubox/logs/ybk_backend/app/ybk_work.log
  fields:
    log_topic: ybk_backend_log
    document_type: ybk_backend
  ignore_older: 24h


#================================ Outputs =====================================
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000