#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/logs/weixingame/app/*.log
  fields:
    log_topic: weixingame_log
    document_type: weixingame
- type: log
  paths:
    - /ubox/logs/ubox-game-web/app/*.log
  fields:
    log_topic: uboxgame_log
    document_type: uboxgame
#================================ Outputs =====================================
#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false


  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000