#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/logs/monk/app/log/*.log
  exclude_files: ['[0-9]{4}-[0-9]{2}-[0-9]{2}.log']
  fields:
    log_topic: monk_log
    document_type: monk
  ignore_older: 24h
#================= Preocessors============================================
processors:
  - drop_fields:
      fields: ["beat","prospector.type","input.type"]
#================================ Outputs =====================================
#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000
