#=========================== Filebeat prospectors =============================
filebeat.inputs:
- type: log
  paths:
    - /ubox/logs/ubox-game-service/app/*.log
  fields:
    log_topic: ubox_game_service
    document_type: ubox_game_service
  ignore_older: 24h

- type: log
  paths:
    - /ubox/apps/deliveryRobot/storage/logs/laravel*.log
  fields:
    log_topic: deliveryRobot
    document_type: deliveryRobot
  ignore_older: 24h
#================================ Outputs =====================================
#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false


  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000