#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/apps/us/logs/us_dailyRolling.log
  fields:
    log_topic: us_dailyRolling
    document_type: us_dailyRolling
  include_lines: ['Cs2ApiProcessor.rapidVend', 'Cs2ApiProcessor.async', 'req']
  #后面两个匹配异步记录
#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000