#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/apps/ka_vs/logs/ka_vs_error.log
    - /ubox/apps/ka_vs/logs/ka_vs.log
  fields:
    log_topic: ka_vs_log
    document_type: ka_vs
#================================ Outputs =====================================
##-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false


  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000
#######################end################33