#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/apps/cds/cds-api/logs/cds-api_dailyRolling.log
  fields:
    log_topic: cds_api_dailyRolling
    document_type: cds_dailyRolling
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  exclude_lines: ['vm to kafka']

- type: log
  paths:
    - /ubox/apps/cds/cds-api/logs/cds-api_exception
  fields:
    log_topic: cds_api_exception
    document_type: cds_exception
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /ubox/logs/cds/cds-os/app/daily-cds-os.log
  document_type: cds_os_dailyRolling
  fields:
    log_topic: cds_os_dailyRolling
    document_type: cds_dailyRolling
  exclude_lines: ['req>>>']
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /ubox/logs/cds/cds-os/app/exception-cds-os.log
  fields:
    log_topic: cds_os_exception
    document_type: cds_exception
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /ubox/logs/cds/cds-wallet/app/daily.log
  fields:
    log_topic: cds_wallet
    document_type: cds_dailyRolling
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /ubox/apps/cds/cds-vs/logs/cds-vs_dailyRolling.log
  fields:
    log_topic: cds_vs_dailyRolling
    document_type: cds_dailyRolling


#================================ Outputs =====================================
#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000