#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/logs/escort/app/escort.log
  fields:
    log_topic: escort_log
    document_type: escort
  multiline.pattern: '^[0-9]{4}\/[0-9]{2}\/[0-9]{2}'
  multiline.negate: true
  multiline.match: after

#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000
