#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  paths:
    - /ubox/logs/parasol/app/parasol.log
    - /ubox/logs/parasol/app/parasol.error.log
  fields:
    log_topic: parasol_log
    document_type: parasol
  multiline.pattern: '^[0-9]{4}\/[0-9]{2}\/[0-9]{2}'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /ubox/apps/workflow/logs/workflow.log
  fields:
    log_topic: workflow_log
    document_type: workflow


#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  key: '%{[agent.hostname]}'
  partition.hash:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000
