#=========================== Filebeat prospectors =============================

filebeat.prospectors:


- input_type: log
  paths:
    - /ubox/logs/wxapi.service/app/wxapi.service.log
  fields:
    log_topic: wxapi_service_log
    document_type: wxapi_service
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after


#================================ Outputs =====================================
#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]
#-----------------------------  kafka   ---------------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["elk03:9092", "elk04:9092", "elk05:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: false

  version: 0.10.0.0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000


